sudo: required
language: node_js
node_js:
- '4'
services:
- docker
script:
- bash build_npm.sh
deploy:
  provider: npm
  email: ellery-newcomer@utulsa.edu
  on: 
    tags: true
  api_key:
    secure: "DSrFmyEAvShdqlTdbXU2QpZOCIfF0DiqO+Grc9U/+wqDta6xJPGgg/WDJZd/1PrpWW9EvNIp66YDBmtlP6a+pH5t3xRKDLr7+qokpAHjQKuY56Jti+xUDoqmweqrf34UkbxnsRDIqgcYYHDCjUdqtC73BiKlvZIEH7LwXpIokYr7p7Gn6f3MjujqYo/2E5xY9m1ukVjSCa+zSk8yW0eAg63vvI4sK17fO5foPEL1AbSLmLT2DHSk+MeK9lw3bQ1wiI8r9g1L1en6Fg/sGPfyXGh/irfDlF0sz9IieNXUFHvnQsJjEgiQ8PPMtna4oJYSSl+MlflZNC7SqOmyB9/s0FNbKtN4/dgu21kRFJlAGLqU1u4r10hWjqG6bpqLhexADpRANVfsZEAip614aDzGQofNc0EDSOkklRlGACAlWXAReVGDGWWSSlnhMB8JgORf9TghocaHuWpOWHJDG6qXkvb2RLBWlk37T76x/B26m817E9+kSwF0g6Z5Cr1xuZTmuYIRfBkDQgqNh4fmE+G+EYX1wyevc4a4AuiUC8mZunwYG4K0aFKdR8WsQcoeKePDJKKxKjV6HmiOlWAdyEG7VM8mSs/mfoB8Qdg8Fv27+QtbM1jAbZ15C7ewJzHyP548jf45XJ1SVHOzsQD1vAb2aTIBtTK7h2gcgjrXTErUYe4="
